---

# install docker
- hosts: plex_server
  roles:
  - role: docker

# backup config
- hosts: plex_server
  roles:
  - role: plex_backup
    when: run_backup is defined and run_backup

# install plex
- hosts: plex_server
  roles:
  - role: plex
